### ISSUE TITLE
メンションテスト用Issue

### ISSUE THREAD

**Issue by osaku-junichiro** [SlackMentionTestOrg/slack-mention-test#1]
Issueコメント内でメンションがどのように表示されるかの確認用

**Comment by osaku-junichiro** [comment]
@KazukiMorisawa 
Slack上の `webhooktest` ルームでこの通知を確認出来たら、チャット等で見れたことをご連絡ください。

**Comment by osaku-junichiro** [comment]
@KazukiMorisawa
Slack上の webhooktest ルームでこの通知を確認出来たら、チャット等で見れたことをご連絡ください。
（Slack アプリの設定を変更後に再送しています。）

**Comment by KazukiMorisawa** [comment]
@osaku-junichiro Slack 自体の通知は来ましたが、メンションとしての通知は来ませんでした。

**Comment by osaku-junichiro** [comment]
@KazukiMorisawa 
- Slack の環境設定から通知の設定を開いてください。
   - ![image](https://user-images.githubusercontent.com/52389044/131446871-5fa78fa2-4099-462e-8a0a-fae4e5100f9e.png)

- キーワードに自分のGitHubのアカウント名を`@`付きで入力してください
   - ![image](https://user-images.githubusercontent.com/52389044/131446759-95eba788-dbdf-4f9c-9bab-0a539bed309f.png)

設定完了しましたら、その旨このIssueコメントで @osaku-junichiro へのメンション付きでコメントをお願いします。

**Comment by KazukiMorisawa** [comment]
@osaku-junichiro 通知の設定をしマイキーワードを登録致しました。

**Comment by osaku-junichiro** [comment]
@KazukiMorisawa （cc @osaku-junichiro ）GitHub Acitons を追加後のテストコメントです。
このコメントをslack上で確認した場合、oviceにてご回答ください。（そのまま口頭での共有も実施したいためです。）

**Comment by KazukiMorisawa** [comment]
@osaku-junichiro (cc @KazukiMorisawa )通知が来たことを確認出来ました。

**Comment by KazukiMorisawa** [comment]
@osaku-junichiro (cc @KazukiMorisawa )Slack がアクティブ状態でのテストです。

**Comment by osaku-junichiro** [comment]
@KazukiMorisawa （cc @osaku-junichiro ）GitHub Acitons を無効化（該当コミットのreset）した後のテストコメントです。

**Comment by osaku-junichiro** [comment]
Organization宛ての購読設定を行った後のコメントテストです。

**Comment by KazukiMorisawa** [comment]
@osaku-junichiro (cc @KazukiMorisawa )マージ後のテストです。
